http: 
  host: localhost
  port: 8000

postgres:
  host: "ep-spring-math-a21ukg78.eu-central-1.aws.neon.tech"
  port: 5432
  user: "neondb_owner"
  password: "ZiA3wBbfVz0g"
  db: "neondb"

jwt:
  secret: "secret" 

example:
  message: "Hello, world!"
